version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - "80:3000"
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    depends_on:
      - mongo
      - redis

  celery-worker:
    build: ./backend
    command: sh -c "sleep 5 && celery -A celery_worker.celery_app worker --loglevel=info"
    depends_on:
      - backend
      - redis
      - mongo

  mongo:
    image: mongo
    ports:
      - "27017:27017"

  mongo-express:
    image: mongo-express
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
    ports:
      - "8081:8081"

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
